package com.changan.multimodal.model.service;

import com.changan.multimodal.model.dto.ModelDescriptor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class ModelRegistryService {

    public List<ModelDescriptor> listModels() {
        return List.of(
                // 目标检测模型
                ModelDescriptor.builder()
                        .modelId("yolov7-detection")
                        .modelName("YOLOv7")
                        .version("1.0.0")
                        .algorithmType("object-detection")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image", "video"))
                        .todo("目标检测 - 支持 mAP、Precision、Recall 评估")
                        .invocationCount(3847)
                        .averageLatency(68.4)
                        .modelCategory("OBJECT_DETECTION")
                        .availableMetrics(List.of("mAP", "Precision", "Recall", "FPS"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("yolov8-detection")
                        .modelName("YOLOv8")
                        .version("8.2.0")
                        .algorithmType("object-detection")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image", "video"))
                        .todo("目标检测 - 支持 mAP、Precision、Recall 评估")
                        .invocationCount(5234)
                        .averageLatency(52.7)
                        .modelCategory("OBJECT_DETECTION")
                        .availableMetrics(List.of("mAP", "Precision", "Recall", "FPS"))
                        .isCustom(false)
                        .build(),
                
                // OCR 模型
                ModelDescriptor.builder()
                        .modelId("dbnet-detector")
                        .modelName("DBNet")
                        .version("2.0")
                        .algorithmType("text-detection")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image"))
                        .todo("文本检测 - 支持识别准确率、拒识率评估")
                        .invocationCount(1892)
                        .averageLatency(115.3)
                        .modelCategory("OCR")
                        .availableMetrics(List.of("Accuracy", "RecognitionRate", "RejectionRate", "Precision"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("crnn-recognizer")
                        .modelName("CRNN")
                        .version("1.1")
                        .algorithmType("text-recognition")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image"))
                        .todo("文本识别 - 支持识别准确率、拒识率评估")
                        .invocationCount(1567)
                        .averageLatency(92.8)
                        .modelCategory("OCR")
                        .availableMetrics(List.of("Accuracy", "RecognitionRate", "RejectionRate"))
                        .isCustom(false)
                        .build(),
                
                // 图像分类模型
                ModelDescriptor.builder()
                        .modelId("mobilenet-classifier")
                        .modelName("MobileNet")
                        .version("v3-large")
                        .algorithmType("image-classification")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image"))
                        .todo("图像分类 - 支持 Top-1/Top-5 准确率评估")
                        .invocationCount(4213)
                        .averageLatency(23.4)
                        .modelCategory("IMAGE_CLASSIFICATION")
                        .availableMetrics(List.of("Top1-Accuracy", "Top5-Accuracy", "Latency"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("resnet50-classifier")
                        .modelName("ResNet50")
                        .version("v1.5")
                        .algorithmType("image-classification")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image"))
                        .todo("图像分类 - 支持 Top-1/Top-5 准确率评估")
                        .invocationCount(3782)
                        .averageLatency(45.6)
                        .modelCategory("IMAGE_CLASSIFICATION")
                        .availableMetrics(List.of("Top1-Accuracy", "Top5-Accuracy"))
                        .isCustom(false)
                        .build(),
                
                // 语义分析模型
                ModelDescriptor.builder()
                        .modelId("bert-base")
                        .modelName("BERT")
                        .version("base-chinese")
                        .algorithmType("semantic-analysis")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("text"))
                        .todo("语义分析 - 支持情感倾向、语义相似度评估")
                        .invocationCount(2891)
                        .averageLatency(156.2)
                        .modelCategory("SEMANTIC_ANALYSIS")
                        .availableMetrics(List.of("Accuracy", "F1-Score", "Precision", "Recall"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("lstm-sentiment")
                        .modelName("LSTM")
                        .version("1.2")
                        .algorithmType("sentiment-analysis")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("text"))
                        .todo("情感分析 - LSTM 架构")
                        .invocationCount(1245)
                        .averageLatency(89.4)
                        .modelCategory("SEMANTIC_ANALYSIS")
                        .availableMetrics(List.of("Accuracy", "F1-Score"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("gru-classifier")
                        .modelName("GRU")
                        .version("1.0")
                        .algorithmType("text-classification")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("text"))
                        .todo("文本分类 - GRU 架构")
                        .invocationCount(892)
                        .averageLatency(78.5)
                        .modelCategory("SEMANTIC_ANALYSIS")
                        .availableMetrics(List.of("Accuracy", "Precision", "Recall"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("transformer-base")
                        .modelName("Transformer")
                        .version("base")
                        .algorithmType("semantic-analysis")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("text"))
                        .todo("语义分析 - Transformer 架构")
                        .invocationCount(1782)
                        .averageLatency(167.3)
                        .modelCategory("SEMANTIC_ANALYSIS")
                        .availableMetrics(List.of("Accuracy", "Perplexity"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("roberta-chinese")
                        .modelName("RoBERTa")
                        .version("chinese-wwm")
                        .algorithmType("semantic-analysis")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("text"))
                        .todo("语义分析 - RoBERTa 系列")
                        .invocationCount(2134)
                        .averageLatency(178.9)
                        .modelCategory("SEMANTIC_ANALYSIS")
                        .availableMetrics(List.of("Accuracy", "F1-Score", "Precision", "Recall"))
                        .isCustom(false)
                        .build(),
                
                // 语音识别模型
                ModelDescriptor.builder()
                        .modelId("deepspeech2")
                        .modelName("DeepSpeech")
                        .version("2.0")
                        .algorithmType("speech-to-text")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("audio"))
                        .todo("语音识别 - DeepSpeech 模型")
                        .invocationCount(1567)
                        .averageLatency(345.6)
                        .modelCategory("SPEECH_RECOGNITION")
                        .availableMetrics(List.of("WER", "CER", "Latency"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("whisper-demo")
                        .modelName("Whisper")
                        .version("large-v3")
                        .algorithmType("speech-to-text")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("audio"))
                        .todo("语音识别 - Whisper 模型，支持多语言")
                        .invocationCount(3456)
                        .averageLatency(289.4)
                        .modelCategory("SPEECH_RECOGNITION")
                        .availableMetrics(List.of("WER", "CER", "Latency"))
                        .isCustom(false)
                        .build(),
                
                // 视觉语言大模型
                ModelDescriptor.builder()
                        .modelId("qwen-vl")
                        .modelName("Qwen-VL")
                        .version("1.5")
                        .algorithmType("vision-language")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image", "text"))
                        .todo("视觉语言大模型 - Qwen-VL，支持动态切换")
                        .invocationCount(678)
                        .averageLatency(1245.3)
                        .modelCategory("VISION_LANGUAGE")
                        .availableMetrics(List.of("BLEU", "ROUGE", "Relevance"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("yi-vl")
                        .modelName("Yi-VL")
                        .version("6B")
                        .algorithmType("vision-language")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image", "text"))
                        .todo("视觉语言大模型 - Yi-VL，支持动态切换")
                        .invocationCount(456)
                        .averageLatency(1123.8)
                        .modelCategory("VISION_LANGUAGE")
                        .availableMetrics(List.of("BLEU", "ROUGE"))
                        .isCustom(false)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("visualglm")
                        .modelName("VisualGLM")
                        .version("6B")
                        .algorithmType("vision-language")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image", "text"))
                        .todo("视觉语言大模型 - VisualGLM，支持动态切换")
                        .invocationCount(389)
                        .averageLatency(1087.2)
                        .modelCategory("VISION_LANGUAGE")
                        .availableMetrics(List.of("BLEU", "ROUGE"))
                        .isCustom(false)
                        .build(),
                
                // 自定义模型
                ModelDescriptor.builder()
                        .modelId("custom-model-v1")
                        .modelName("甲方自研模型")
                        .version("1.0.0")
                        .algorithmType("custom")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image", "text", "audio"))
                        .todo("甲方自研模型 - 支持标准化模型接口")
                        .invocationCount(234)
                        .averageLatency(189.5)
                        .modelCategory("CUSTOM")
                        .availableMetrics(List.of("Accuracy", "Latency"))
                        .isCustom(true)
                        .build(),
                ModelDescriptor.builder()
                        .modelId("custom-finetuned")
                        .modelName("微调改进模型")
                        .version("2.1.0")
                        .algorithmType("custom-finetuned")
                        .deploymentStatus("RUNNING")
                        .supportedModalities(List.of("image"))
                        .todo("基于现有模型微调改进 - 支持标准化模型接口")
                        .invocationCount(189)
                        .averageLatency(156.7)
                        .modelCategory("CUSTOM")
                        .availableMetrics(List.of("Accuracy", "mAP"))
                        .isCustom(true)
                        .build()
        );
    }

    public ModelDescriptor analyzeModel(String onnxFileName, long fileSize) {
        return ModelDescriptor.builder()
                .modelId("onnx-" + System.currentTimeMillis())
                .modelName(onnxFileName.replace(".onnx", ""))
                .version("1.0.0")
                .algorithmType("onnx-inferred")
                .deploymentStatus("ANALYZED")
                .supportedModalities(List.of("image", "tensor"))
                .todo("通过 ONNX 解析获得，可接入标准化接口")
                .invocationCount(0)
                .averageLatency(0.0)
                .modelCategory("UNCLASSIFIED")
                .availableMetrics(List.of("Latency", "Throughput"))
                .isCustom(false)
                .build();
    }
}
